openapi: 3.0.0
info:
  title: Rutas de Carrito
  version: 1.0.0
paths:
  /carts/{cid}:
    get:
      summary: Obtiene un carrito por ID
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: integer
      responses:
        '200':
          description: Detalles del carrito
    put:
      summary: Actualiza un carrito por ID
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: integer
      responses:
        '200':
          description: Carrito actualizado correctamente
    delete:
      summary: Elimina un carrito por ID
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: integer
      responses:
        '200':
          description: Carrito eliminado correctamente
  /cart/{cid}/products/{pid}:
    post:
      summary: Agrega un producto al carrito
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: integer
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: integer
      responses:
        '200':
          description: Producto agregado al carrito correctamente
    delete:
      summary: Elimina un producto del carrito
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: integer
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: integer
      responses:
        '200':
          description: Producto eliminado del carrito correctamente
    put:
      summary: Actualiza la cantidad de un producto en el carrito
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: integer
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: integer
        - name: units
          in: path
          required: true
          description: Cantidad del producto
          schema:
            type: integer
      responses:
        '200':
          description: Cantidad de producto en el carrito actualizada correctamente
  /cart/{cid}/purchase:
    post:
      summary: Finaliza la compra del carrito
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: integer
      responses:
        '200':
          description: Compra del carrito finalizada correctamente